default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  host: 127.0.0.1
  port: 3306
  # Change these credentials to match your own environment
  username: root
  password: root

development:
  <<: *default
  database: well_dev

test:
  <<: *default
  database: well_test

production:
  <<: *default
  database: well